[2024-08-05T13:05:36.534+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:05:36.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-03T15:00:00+00:00 [queued]>
[2024-08-05T13:05:36.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-03T15:00:00+00:00 [queued]>
[2024-08-05T13:05:36.623+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-05T13:05:36.655+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2022-08-03 15:00:00+00:00
[2024-08-05T13:05:36.682+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1644) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T13:05:36.685+0000] {standard_task_runner.py:64} INFO - Started process 1685 to run task
[2024-08-05T13:05:36.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2022-08-03T15:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpugndemx4']
[2024-08-05T13:05:36.695+0000] {standard_task_runner.py:91} INFO - Job 185: Subtask predict
[2024-08-05T13:05:36.815+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2022-08-03T15:00:00+00:00 [running]> on host db70dacab446
[2024-08-05T13:05:37.074+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2022-08-03T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-03T15:00:00+00:00'
[2024-08-05T13:05:37.087+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:05:37.170+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:05:37.175+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/predict.py", line 54, in predict
    with open(path+files) as f:
              ~~~~^~~~~~
TypeError: can only concatenate str (not "list") to str
[2024-08-05T13:05:37.227+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=predict, run_id=scheduled__2022-08-03T15:00:00+00:00, execution_date=20220803T150000, start_date=20240805T130536, end_date=20240805T130537
[2024-08-05T13:05:37.274+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 185 for task predict (can only concatenate str (not "list") to str; 1685)
[2024-08-05T13:05:37.344+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:05:37.388+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:05:37.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
