[2024-08-05T13:18:40.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:18:40.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-08-05T13:02:34.024518+00:00 [queued]>
[2024-08-05T13:18:41.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-08-05T13:02:34.024518+00:00 [queued]>
[2024-08-05T13:18:41.097+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-05T13:18:42.425+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2024-08-05 13:02:34.024518+00:00
[2024-08-05T13:18:42.452+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T13:18:42.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'manual__2024-08-05T13:02:34.024518+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpbvexpw1m']
[2024-08-05T13:18:42.468+0000] {standard_task_runner.py:64} INFO - Started process 295 to run task
[2024-08-05T13:18:42.481+0000] {standard_task_runner.py:91} INFO - Job 209: Subtask predict
[2024-08-05T13:18:42.716+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict manual__2024-08-05T13:02:34.024518+00:00 [running]> on host db70dacab446
[2024-08-05T13:18:43.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T13:02:34.024518+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T13:02:34.024518+00:00'
[2024-08-05T13:18:43.038+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:18:43.145+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:18:43.147+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/predict.py", line 55, in predict
    with open(path+files) as f:
              ~~~~^~~~~~
TypeError: can only concatenate str (not "list") to str
[2024-08-05T13:18:43.193+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=predict, run_id=manual__2024-08-05T13:02:34.024518+00:00, execution_date=20240805T130234, start_date=20240805T131841, end_date=20240805T131843
[2024-08-05T13:18:43.233+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 209 for task predict (can only concatenate str (not "list") to str; 295)
[2024-08-05T13:18:43.270+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:18:43.318+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:18:43.324+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
