[2024-08-05T13:00:02.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:00:02.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-07-21T15:00:00+00:00 [queued]>
[2024-08-05T13:00:02.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-07-21T15:00:00+00:00 [queued]>
[2024-08-05T13:00:02.151+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:00:02.174+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2022-07-21 15:00:00+00:00
[2024-08-05T13:00:02.186+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=836) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T13:00:02.187+0000] {standard_task_runner.py:64} INFO - Started process 849 to run task
[2024-08-05T13:00:02.190+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2022-07-21T15:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpv3n_v1ww']
[2024-08-05T13:00:02.191+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask predict
[2024-08-05T13:00:02.291+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2022-07-21T15:00:00+00:00 [running]> on host db70dacab446
[2024-08-05T13:00:02.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2022-07-21T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-21T15:00:00+00:00'
[2024-08-05T13:00:02.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:00:02.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:00:02.514+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/predict.py", line 54, in predict
    with open(path+files) as f:
              ~~~~^~~~~~
TypeError: can only concatenate str (not "list") to str
[2024-08-05T13:00:02.574+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=predict, run_id=scheduled__2022-07-21T15:00:00+00:00, execution_date=20220721T150000, start_date=20240805T130002, end_date=20240805T130002
[2024-08-05T13:00:02.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task predict (can only concatenate str (not "list") to str; 849)
[2024-08-05T13:00:02.644+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:00:02.677+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:00:02.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
